### ISSUE TITLE
New Keyboard Layout

### ISSUE THREAD

**Issue by L0adImag3** [Seytonic/malduino#25]
Hi :)

I would like to contribute a new locale (CH_de) to the project. The only instruction i could find to create a new locale was this [https://github.com/Nurrl/LocaleKeyboard.js/wiki/How-to-create-a-locale-%3F!](url).

I downloaded the sample file but im not sure hot to find the right hex/dec values of my keyboard layout for the _asciimap variable and the initAltGr() function. 

Can anyone point me in the right direction where or how i can find the right values?

**Comment by L0adImag3** [comment]
okay i figured it out myself :)

**Comment by Chr1s28** [comment]
> okay i figured it out myself :)

Hey
I would be interested in the locale for CH_de. Could you help me or even give me the file?

**Comment by Molnes** [comment]
@moswed is it possible to tell me how you found the right values? Because I'm trying to create a new locale for Norwegian bokmål (nb_NO)

**Comment by Chr1s28** [comment]
@Retardur So i figured it out by myself and the way i did it was by looking which characters are wrong and just trial and error to see what it's supposed to be. For example if its writing ! instead of * you just look where it does write * and take the keycode from there. Hope that helps. And btw for AltGR characters you just look up the ASCII decimal codes for the characters that need it and at them to the other AltGR characters

**Comment by Molnes** [comment]
@Chr1s28 thank you

**Comment by justjackstuff** [comment]
@Retardur Did you make the nb_NO locale im interested

**Comment by Neoministein** [comment]
@Chr1s28 
Hi,
I would also be interested in the locale for CH_de file. Would it be possible that you could send me the file or help me create one my self?

**Comment by Chr1s28** [comment]
@Neoministein So it has been a while since i've done anything with the malduino but i found my file and uploaded it. Heres the link:
https://gist.github.com/Chr1s28/4b9cecd902107bdfbe07004dce3edef3

**Comment by Neoministein** [comment]
@Chr1s28 Thanks you very much you are amazing!
